# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a10d3e861096adcf5bcaaa52a9e74cecb153c9ada3530e06b86ad952008202f99a9a6a367ae777ffb7fc4fef0173a1130155a950d256b9092a2d50c6a5fd1cb

test:
  secret_key_base: 23c0375cb0c3b4d32e5741a6eabd59ed76b748b870af973ab6532cf2f057725b47e97597da57e56d4c5473f16e272bafa2bf396d6fdaa448c257b14048223177

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
